export const CONNECTED_TO_BACKEND = 'CONNECTED_TO_BACKEND';
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const SIGN_IN_EMAIL = 'SIGN_IN_EMAIL';
export const SIGNIN_EMAIL_SUCCESS = 'SIGNIN_EMAIL_SUCCESS';
export const SIGNIN_EMAIL_FAILURE = 'SIGNIN_EMAIL_FAILURE';